// Generated by https://quicktype.io

export interface Category {
    $id?:          string;
    categoryID:   number;
    categoryName: string;
    question?:     null;
}


export interface UserAnswers {
   
    answerID:   number;
    questionID: number;
    question?:  string;
}